#!/usr/bin/perl -w
# Copyright 2010 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation. No representations are made about the suitability of this
# software for any purpose. It is provided "as is" without express or
# implied warranty.
#
################################################################################

use DBI;
use strict;

our $VERSION = '0.01';

# edit accordingly...
my $dsn  = '';
my $user = '';
my $pass = '';

my $dbh = DBI->connect($dsn, $user, $pass) ||
    die "Could not connect to $dsn - $DBI::errstr\n";

my $SQL = <<EOSQL;
select profileevent_id, profileevent_identifier
from mt_profileevent
EOSQL

my $sth = $dbh->prepare($SQL) || die "$DBI::errstr\n";
$sth->execute() || die $sth->errstr(), "\n";
my %seen;
my @seenids;
while (my $row = $sth->fetchrow_hashref()) {
    if ($seen{$row->{profileevent_identifier}}++) {
        push(@seenids, $row->{profileevent_id});
    }
}
if (@seenids) {
    $SQL = 'delete from mt_profileevent where profileevent_id = ?';
    $sth = $dbh->prepare($SQL) || die $DBI::errstr, "\n";
    for my $id (@seenids) {
        $sth->execute($id) || die $sth->errstr(), "\n";
    }
}

